name: 'run-chaos'

on:
  workflow_dispatch:

jobs:
  run-chaos:
    runs-on: ubuntu-latest
    steps:
      - name: Azure login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Set up kubelogin for non-interactive login
        uses: azure/use-kubelogin@v1
        with:
          kubelogin-version: 'v0.0.25'
      - name: Get K8s context
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ vars.RESOURCE_GROUP }}
          cluster-name: ${{ vars.RESOURCE_GROUP }}-aks
          admin: 'false'
          use-kubelogin: 'true'
      - name: Run chaos
        run: |
          kubectl delete workflow pod-delete -n litmus
          kubectl delete workflow pod-hog -n litmus
          kubectl apply -f ./chaos-engineering/experiments/pod-delete.yaml